### ISSUE TITLE
Uncaught TypeError: Cannot use 'in' operator to search for 'dataset' in null

### ISSUE THREAD

**Issue by lemonash** [lloiser/go-debug#1]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.4.0
**System**: Linux Mint
**Thrown From**: [go-debug](https://github.com/lloiser/go-debug) package, v0.0.2

### Stack Trace

Uncaught TypeError: Cannot use 'in' operator to search for 'dataset' in null

```
At /home/lemonash/.atom/packages/go-debug/lib/utils.js:30

TypeError: Cannot use 'in' operator to search for 'dataset' in null
    at getDeep (/home/lemonash/.atom/packages/go-debug/lib/utils.js:30:14)
    at elementPropInHierarcy (/home/lemonash/.atom/packages/go-debug/lib/utils.js:41:9)
    at Panel._onStacktraceClick (/home/lemonash/.atom/packages/go-debug/lib/panel.js:139:17)
```

### Commands

```
     -1:26.3.0 go-debug:continue (div.go-debug-panel)
  4x -1:24.5.0 go-debug:step (div.go-debug-panel)
     -1:22.2.0 go-debug:next (div.go-debug-panel)
     -1:15.7.0 go-debug:restart (div.go-debug-panel)
     -1:13.8.0 go-debug:runPackageTests (div.go-debug-panel)
     -1:12.2.0 go-debug:runPackage (div.go-debug-panel)
     -1:10.2.0 go-debug:runPackageTests (div.go-debug-panel)
     -1:09.4.0 go-debug:runPackage (div.go-debug-panel)
     -1:04.6.0 core:save (button.btn.btn-default)
  4x -1:01.4.0 core:cancel (button.btn.btn-default)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "themes": [
      "cold-ui",
      "monokai-seti"
    ]
  }
}
```

### Installed Packages

```coffee
# User
cold-ui, v1.4.0
dash, v1.6.0
file-icons, v1.6.14
go-debug, v0.0.2
go-plus, v3.5.2
highlight-line, v0.11.0
monokai-seti, v0.7.0

# Dev
No dev packages
```

**Comment by lloiser** [comment]
thanks I have noticed it too.. fix is on the way.
