### ISSUE TITLE
Failed to start delve

### ISSUE THREAD

**Issue by ctrath** [lloiser/go-debug#112]
Only when I add a breakpoint, I see the following:

```
Failed to start delve with config "Test"
  Error: TypeError: Cannot read property 'children' of undefined
delve closed with code 0
```

I tried to restart atom.  I looked for lingering dlv processes and found none.  I tried to remove debug.test and that didn't help.

I'm assuming there is something lingering in the background, but I'm unsure what it may be.  The debugger was working, then all of a sudden I see this message every time I set a breakpoint and run the "Test" config.

Config:
macOS Sierra: 10.12.6
Atom 1.19.4 x64
go-debug 1.5.0
delve 1.0.0-rc.1
go version go1.8.3 darwin/amd64

**Comment by lloiser** [comment]
Can you provide the code that you tried to debug?

Now lets try to debug the problem:
Open the developer tools of atom using `alt-cmd-i`, click the `Sources` tab, open the `go-debug/lib/debugger.js` using `cmd-p`/`ctrl-p` and add a breakpoint on line 73 by clicking on the line number.
The line looks something like this `this.addOutputMessage('Failed to start delve with config .....`
Then do whatever you did previously when you got this error. Now the developer tools should highlight the line 73, switch to the `Console` tab and type `err` and press enter. Copy/paste whatever is shown in there into this issue here.

**Comment by lloiser** [comment]
With the new version (1.5.1) I have added a console.log statement so that you can easily spot the actual error in the `Console` tab. Please copy/paste it here.

**Comment by b4dnewz** [comment]
Hi, I've the same issue that occur when I set a breakpoint somewhere in the code (the code itself is working) and than trying to debug (F5) I get this error:
```
Failed to start delve with config "Debug"
  Error: TypeError: Cannot read property 'children' of undefined
delve closed with code 0
```

This is the inspector output:
```
go-debug start TypeError: Cannot read property 'children' of undefined
    at Object._interface [as interface] (file:///C:/Users/username/.atom/packages/go-debug/lib/delve-variables.js:176:45)
    at Object.variable (file:///C:/Users/username/.atom/packages/go-debug/lib/delve-variables.js:66:28)
    at file:///C:/Users/username/.atom/packages/go-debug/lib/delve-variables.js:155:43
    at Array.map (native)
    at Object.struct (file:///C:/Users/username/.atom/packages/go-debug/lib/delve-variables.js:154:40)
    at Object.variable (file:///C:/Users/username/.atom/packages/go-debug/lib/delve-variables.js:66:28)
    at Object.ptr (file:///C:/Users/username/.atom/packages/go-debug/lib/delve-variables.js:106:41)
    at Object.variable (file:///C:/Users/username/.atom/packages/go-debug/lib/delve-variables.js:66:28)
    at Object._interface [as interface] (file:///C:/Users/username/.atom/packages/go-debug/lib/delve-variables.js:181:41)
    at Object.variable (file:///C:/Users/username/.atom/packages/go-debug/lib/delve-variables.js:66:28)
    at file:///C:/Users/username/.atom/packages/go-debug/lib/delve-variables.js:155:43
    at Array.map (native)
    at Object.struct (file:///C:/Users/username/.atom/packages/go-debug/lib/delve-variables.js:154:40)
    at Object.variable (file:///C:/Users/username/.atom/packages/go-debug/lib/delve-variables.js:66:28)
    at Object.ptr (file:///C:/Users/username/.atom/packages/go-debug/lib/delve-variables.js:106:41)
    at Object.variable (file:///C:/Users/username/.atom/packages/go-debug/lib/delve-variables.js:66:28)
    at file:///C:/Users/username/.atom/packages/go-debug/lib/delve-variables.js:25:23
    at Array.forEach (native)
    at Object.create (file:///C:/Users/username/.atom/packages/go-debug/lib/delve-variables.js:24:16)
    at file:///C:/Users/username/.atom/packages/go-debug/lib/delve-session.js:197:29
    at process._tickDomainCallback (internal/process/next_tick.js:129:7)
```

The error seems to come from [lib/delve-variables.js#L176](https://github.com/lloiser/go-debug/blob/f144d15ce8058d0feb0d3dca16e4f6430d3b8610/lib/delve-variables.js#L176), hope this helps.

**Comment by lloiser** [comment]
Thx for this I finally found the error.
go-debug tries to display the native `error` nicely but it fails (with the error you see above) if the error is nested inside e.g. a slice or a struct.
Fix is coming soon.

**Comment by b4dnewz** [comment]
i'm really glad that helped, I'll wait for the next update to see it working again. 
Many thanks and by the way **great** job.
