### ISSUE TITLE
Failed to get version of dlv

### ISSUE THREAD

**Issue by anshprat** [lloiser/go-debug#117]
Hi,

Seeing the following error in Atom console:
```

go-debug Failed to get "dlv" Error: Failed to get version of dlv:
  Exit code: 127
  Error: "spawn EACCES"
  Stderr: ""
  Stdout: ""
  Dlv path: "/Users/anshup/code/go/bin"
    at /Users/anshup/.atom/packages/go-debug/lib/delve-get.js:39:31
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

As a result, I guess thats the reason I cannot see debug console.

**Comment by lloiser** [comment]
pls have a look at #52. If this fixes your problem, close this one :)

**Comment by lloiser** [comment]
Closing due to inactivity.
