### ISSUE TITLE
Uncaught Error: watch ~/Workspace/partnership-blockchain-integration ENOSPC

### ISSUE THREAD

**Issue by Vladislav-Zolotaryov** [lloiser/go-debug#119]
[Enter steps to reproduce:]

1. Open any Go file
2. See the error notification

**Atom**: 1.22.1 x64
**Electron**: 1.6.15
**OS**: Linux Mint
**Thrown From**: [go-debug](https://github.com/lloiser/go-debug) package 1.5.2

### Stack Trace

Uncaught Error: watch /home/wz/Workspace/partnership-blockchain-integration ENOSPC

```
At events.js:160

Error: watch /home/wz/Workspace/partnership-blockchain-integration ENOSPC
    at exports._errnoException (util.js:1022:11)
    at FSWatcher.start (fs.js:1316:19)
    at Object.fs.watch (fs.js:1341:11)
    at createFsWatchInstance (/packages/go-debug/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/packages/go-debug/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/packages/go-debug/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at FSWatcher.NodeFsHandler._handleDir (/packages/go-debug/node_modules/chokidar/lib/nodefs-handler.js:407:19)
    at /packages/go-debug/node_modules/chokidar/lib/nodefs-handler.js:455:19)
    at /packages/go-debug/node_modules/chokidar/lib/nodefs-handler.js:460:16)
    at FSReqWrap.oncomplete (fs.js:112:15)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.30.9 
atom-ide-ui 0.6.0 
atom-typescript 11.0.10 
atom-wrap-in-tag 0.6.0 
autocomplete-bash-builtins 0.3.5 
autocomplete-modules 1.8.0 
autocomplete-paths 2.12.1 
busy-signal 1.4.3 
cursor-history 0.12.0 
emmet 2.4.3 
es6-javascript 1.0.0 
go-debug 1.5.2 
go-plus 5.6.0 
go-signature-statusbar 1.2.3 
ide-go 0.4.0 
ide-java 0.7.0 
ide-typescript 0.7.1 
intentions 1.1.5 
java-generator 2.2.3 
js-hyperclick 1.12.2 
js-hyperclick-project-path 1.12.0 
linter 2.2.0 
linter-eslint 8.4.0 
linter-js-standard 4.1.0 
linter-less 2.6.0 
linter-tslint 1.9.0 
linter-ui-default 1.6.10 
local-history 4.3.1 
project-manager 3.3.5 
related 0.3.5 
script 3.17.3 
set-syntax 0.4.0 
sync-settings 0.8.3 
```

**Comment by lloiser** [comment]
https://github.com/lloiser/go-debug/issues/73

If this does not help, please reopen.
