### ISSUE TITLE
does not work on windows

### ISSUE THREAD

**Issue by smallnest** [lloiser/go-debug#12]
My environment:
1. windows 10
2. atom 1.6.2
3. installed delve and add delve in the path 
4. godebug 0.1.5

It shows go-debug has been installed in setting page but go-debug has not displayed in Pakcages menu.

And  when I opened a main.go file, and press F5, there is no any debug panels.

**Comment by lloiser** [comment]
The panel should be visible after installing it... maybe something went wrong.
You can show/hide the panel using `ctrl-k ctrl-g`.

**Comment by lloiser** [comment]
But it seems to be a nice feature to show the panel whenever you start delve (using `F5` for debug or `ctrl-F5` for test)

**Comment by smallnest** [comment]
It shows go-debug has not started and it existed:

	consumeGoconfig (service) {
		goconfig = service;
		goconfig.locator.findTool("dlv").then((p) => {
			path = p;
			this.start();
		});
	},

	start() {
		if (!dependenciesInstalled || !path) {
			alert("hello")
			return;
		}

I

**Comment by lloiser** [comment]
go-debug depends on two things in the beginning:

* Install the dependencies: https://github.com/lloiser/go-debug/blob/master/lib/main.js#L20
* get the `go-config` service to locate delve: https://github.com/lloiser/go-debug/blob/master/lib/main.js#L40

once both are done the panel should start.

So either the dependencies failed (which should log something into the console) or `go-config` couldn't find delve...

**Comment by smallnest** [comment]
Thanks.  The two passes and I found the below debug alert has not been triggerr. 
```
panel = require("./panel.jsx");
alert("hello")
```
I need to investigate it more but I am not familiar with node.js

**Comment by lloiser** [comment]
I don't write any log files. Open the developer tools in atom (`alt-cmd-i` /  `alt-ctrl-i`) and check the console. Do you see any logs there?

**Comment by smallnest** [comment]
Yes, Thanks. The log is:

```
TypeError: Cannot read property 'Component' of undefined(…)
Uncaught (in promise) TypeError: Cannot read property 'Component' of undefined
    at Object.<anonymous> (C:\Users\smallnest\.atom\packages\go-debug\lib\variables.jsx:64:23)
    at Module._compile (C:\Users\smallnest\AppData\Local\atom\app-1.6.2\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (C:\Users\smallnest\AppData\Local\atom\app-1.6.2\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (C:\Users\smallnest\AppData\Local\atom\app-1.6.2\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (C:\Users\smallnest\.atom\packages\go-debug\lib\panel.jsx:25:21)
    at Module._compile (C:\Users\smallnest\AppData\Local\atom\app-1.6.2\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (C:\Users\smallnest\AppData\Local\atom\app-1.6.2\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (C:\Users\smallnest\AppData\Local\atom\app-1.6.2\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.start (C:/Users/smallnest/.atom/packages/go-debug/lib/main.js:60:11)
    at C:/Users/smallnest/.atom/packages/go-debug/lib/main.js:42:9
    at process._tickCallback (node.js:368:9)
```

**Comment by lloiser** [comment]
see #8

**Comment by smallnest** [comment]
Thanks a lot.

The reason is same to #3. Disable hyperclick and go-debug works well.


> The "hyperclick" package has been superseded by the "nuclide" package. If you'd like to use Hyperclick, install the "nuclide" package and disable the features you don't need.
