### ISSUE TITLE
Uncaught Error: watch ~/devel/go/packages/src/kubevirt.io/kubevirt ENOSPC

### ISSUE THREAD

**Issue by vladikr** [lloiser/go-debug#120]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.0 x64
**Electron**: 1.6.15
**OS**: "Fedora release
**Thrown From**: [go-debug](https://github.com/lloiser/go-debug) package 1.5.2

### Stack Trace

Uncaught Error: watch /home/vladikr/devel/go/packages/src/kubevirt.io/kubevirt ENOSPC

```
At events.js:160

Error: watch /home/vladikr/devel/go/packages/src/kubevirt.io/kubevirt ENOSPC
    at exports._errnoException (util.js:1022:11)
    at FSWatcher.start (fs.js:1316:19)
    at Object.fs.watch (fs.js:1341:11)
    at createFsWatchInstance (/packages/go-debug/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/packages/go-debug/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/packages/go-debug/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at FSWatcher.NodeFsHandler._handleDir (/packages/go-debug/node_modules/chokidar/lib/nodefs-handler.js:407:19)
    at /packages/go-debug/node_modules/chokidar/lib/nodefs-handler.js:455:19)
    at /packages/go-debug/node_modules/chokidar/lib/nodefs-handler.js:460:16)
    at FSReqWrap.oncomplete (fs.js:112:15)
```

### Commands

```
     -2:47.5.0 application:add-project-folder (input.hidden-input)
     -1:27.5.0 golang:update-tools (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
busy-signal 1.4.3 
go-debug 1.5.2 
go-plus 5.6.0 
go-signature-statusbar 1.2.3 
hyperclick 0.1.5 
ide-c 0.0.2 
ide-go 0.4.0 
ide-python 0.3.0 
intentions 1.1.5 
linter 2.2.0 
linter-ui-default 1.6.10 
vim-mode 0.66.0 
```

**Comment by lloiser** [comment]
This should be fixed with the latest version 1.6.0
