### ISSUE TITLE
go-debug failed to get "dlv"

### ISSUE THREAD

**Issue by PigPigAutumn** [lloiser/go-debug#122]
go-debug version: 1.5.2
OS: ubuntu 16.04

I installed go-debug on atom, but go-debug does not ready and the console show:
`go-debug Failed to get "dlv" TypeError: Cannot create property 'timeout' on string 'project'
    at Executor.ensureOptions (/home/pigpigautumn/.atom/packages/go-plus/executor.js:168:7)
    at Promise (/home/pigpigautumn/.atom/packages/go-plus/executor.js:67:29)
    at Executor.exec (/home/pigpigautumn/.atom/packages/go-plus/executor.js:66:12)
    at getVersion (/home/pigpigautumn/.atom/packages/go-debug/lib/delve-get.js:31:30)
    at located (/home/pigpigautumn/.atom/packages/go-debug/lib/delve-get.js:23:14)`

but I can use `dlv` command in terminal
so what can I do to make go-debug find my dlv?
Thanks.

**Comment by lloiser** [comment]
Should be fixed with 1.5.3. Please update go-debug.
