### ISSUE TITLE
go-debug Failed

### ISSUE THREAD

**Issue by Dollarsss** [lloiser/go-debug#123]
toggle the dev tools panel,and i see
`go-debug Failed to get "dlv" TypeError: Cannot create property 'timeout' on string 'project'
    at Executor.ensureOptions (/Users/cjy/.atom/packages/go-plus/executor.js:168:7)
    at Promise (/Users/cjy/.atom/packages/go-plus/executor.js:67:29)
    at Executor.exec (/Users/cjy/.atom/packages/go-plus/executor.js:66:12)
    at getVersion (/Users/cjy/.atom/packages/go-debug/lib/delve-get.js:31:30)
    at located (/Users/cjy/.atom/packages/go-debug/lib/delve-get.js:23:14)`

**Comment by lloiser** [comment]
Should be fixed with 1.5.3. Please update go-debug.
