### ISSUE TITLE
Uncaught Error: watch ~/github/composer ENOSPC

### ISSUE THREAD

**Issue by cnliuxud** [lloiser/go-debug#127]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.3 x64
**Electron**: 1.6.15
**OS**: Ubuntu 16.04.3
**Thrown From**: [go-debug](https://github.com/lloiser/go-debug) package 1.5.3

### Stack Trace

Uncaught Error: watch /home/blockchain/github/composer ENOSPC

```
At events.js:160

Error: watch /home/blockchain/github/composer ENOSPC
    at exports._errnoException (util.js:1022:11)
    at FSWatcher.start (fs.js:1316:19)
    at Object.fs.watch (fs.js:1341:11)
    at createFsWatchInstance (/packages/go-debug/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/packages/go-debug/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/packages/go-debug/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at FSWatcher.NodeFsHandler._handleDir (/packages/go-debug/node_modules/chokidar/lib/nodefs-handler.js:407:19)
    at /packages/go-debug/node_modules/chokidar/lib/nodefs-handler.js:455:19)
    at /packages/go-debug/node_modules/chokidar/lib/nodefs-handler.js:460:16)
    at FSReqWrap.oncomplete (fs.js:112:15)
```

### Commands

```
```

### Non-Core Packages

```
atom-clock 0.1.16 
busy-signal 1.4.3 
composer 0.5.0 
composer-atom-plugin 0.7.1 
docblockr 0.13.5 
docker 0.8.0 
file-icons 2.1.15 
go-debug 1.5.3 
go-plus 5.7.2 
highlight-selected 0.13.1 
Hydrogen 2.2.1 
ide-go 0.4.0 
intentions 1.1.5 
linter 2.2.0 
linter-eslint 8.4.0 
linter-ui-default 1.6.10 
todo-show 2.1.0 
```

**Comment by lloiser** [comment]
This should be fixed with the latest version 1.6.0
