### ISSUE TITLE
Uncaught Error: watch ~/go/src/github.com/RiverbedTechnology/sdp-ui ENOSPC

### ISSUE THREAD

**Issue by petmat425** [lloiser/go-debug#129]
[Enter steps to reproduce:]

1. This seems to occur each time I open a '.go' file. I upgraded Atom from v1.22 to v1.23, but this didn't seem to make a difference.

**Atom**: 1.23.3 x64
**Electron**: 1.6.15
**OS**: Ubuntu 16.04.3
**Thrown From**: [go-debug](https://github.com/lloiser/go-debug) package 1.5.3

### Stack Trace

Uncaught Error: watch /home/pmatthews/go/src/github.com/RiverbedTechnology/sdp-ui ENOSPC

```
At events.js:160

Error: watch /home/pmatthews/go/src/github.com/RiverbedTechnology/sdp-ui ENOSPC
    at exports._errnoException (util.js:1022:11)
    at FSWatcher.start (fs.js:1316:19)
    at Object.fs.watch (fs.js:1341:11)
    at createFsWatchInstance (/packages/go-debug/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/packages/go-debug/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/packages/go-debug/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at FSWatcher.NodeFsHandler._handleDir (/packages/go-debug/node_modules/chokidar/lib/nodefs-handler.js:407:19)
    at /packages/go-debug/node_modules/chokidar/lib/nodefs-handler.js:455:19)
    at /packages/go-debug/node_modules/chokidar/lib/nodefs-handler.js:460:16)
    at FSReqWrap.oncomplete (fs.js:112:15)
```

### Commands

```
```

### Non-Core Packages

```
busy-signal 1.4.3 
go-build 0.2.1 
go-debug 1.5.3 
go-plus 5.7.2 
go-signature-statusbar 1.2.3 
intentions 1.1.5 
language-protobuf 0.7.1 
linter 2.2.0 
linter-golinter 1.2.2 
linter-ui-default 1.6.10 
```

**Comment by lloiser** [comment]
This should be fixed with the latest version 1.6.0
