### ISSUE TITLE
go-debug not starting properly

### ISSUE THREAD

**Issue by docbobo** [lloiser/go-debug#16]
Although it worked in the past, recent version(s) of go-debug do not start properly on my machine. I tried to debug this but I didn't get that far. However, here's the stacktrace that I got:

```
TypeError: Cannot read property 'Component' of undefined
    at Object.<anonymous> (/Users/bpruessm/.atom/packages/go-debug/lib/variables.jsx:64:23)
    at Module.contents.overrideModuleCompile.Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.keys.forEach.Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/bpruessm/.atom/packages/go-debug/lib/panel.jsx:27:21)
    at Module.contents.overrideModuleCompile.Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.keys.forEach.Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.start (/Users/bpruessm/.atom/packages/go-debug/lib/main.js:66:11)
    at /Users/bpruessm/.atom/packages/go-debug/lib/main.js:26:9
```

**Comment by lloiser** [comment]
#8 #12

**Comment by docbobo** [comment]
Thanks. I also arrived at the conclusion that hyperclick is causing this.
