### ISSUE TITLE
Uncaught TypeError: Cannot read property 'nodeName' of undefined

### ISSUE THREAD

**Issue by olebedev** [lloiser/go-debug#18]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.7.1
**System**: Mac OS X 10.10.5
**Thrown From**: [go-debug](https://github.com/lloiser/go-debug) package, v0.1.7

### Stack Trace

Uncaught TypeError: Cannot read property 'nodeName' of undefined

```
At /Users/olebedev/.atom/packages/go-debug/node_modules/react-for-atom/node_modules/react/lib/ReactErrorUtils.js:53

TypeError: Cannot read property 'nodeName' of undefined
    at CommandLogger.module.exports.CommandLogger.logCommand (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/notifications/lib/command-logger.js:81:38)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/notifications/lib/command-logger.js:33:24
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:20)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
    at Panel.onCommandClick (/Users/olebedev/.atom/packages/go-debug/lib/panel.jsx:285:18)
    at Object.invokeGuardedCallback (/Users/olebedev/.atom/packages/go-debug/node_modules/react-for-atom/node_modules/react/lib/ReactErrorUtils.js:27:12)
    at executeDispatch (/Users/olebedev/.atom/packages/go-debug/node_modules/react-for-atom/node_modules/react/lib/EventPluginUtils.js:79:21)
    at Object.executeDispatchesInOrder (/Users/olebedev/.atom/packages/go-debug/node_modules/react-for-atom/node_modules/react/lib/EventPluginUtils.js:102:5)
    at executeDispatchesAndRelease (/Users/olebedev/.atom/packages/go-debug/node_modules/react-for-atom/node_modules/react/lib/EventPluginHub.js:43:22)
    at executeDispatchesAndReleaseTopLevel (/Users/olebedev/.atom/packages/go-debug/node_modules/react-for-atom/node_modules/react/lib/EventPluginHub.js:54:10)
    at Array.forEach (native)
    at forEachAccumulated (/Users/olebedev/.atom/packages/go-debug/node_modules/react-for-atom/node_modules/react/lib/forEachAccumulated.js:23:9)
    at Object.EventPluginHub.processEventQueue (/Users/olebedev/.atom/packages/go-debug/node_modules/react-for-atom/node_modules/react/lib/EventPluginHub.js:259:7)
    at runEventQueueInBatch (/Users/olebedev/.atom/packages/go-debug/node_modules/react-for-atom/node_modules/react/lib/ReactEventEmitterMixin.js:18:18)
    at Object.ReactEventEmitterMixin.handleTopLevel [as _handleTopLevel] (/Users/olebedev/.atom/packages/go-debug/node_modules/react-for-atom/node_modules/react/lib/ReactEventEmitterMixin.js:34:5)
    at handleTopLevelWithoutPath (/Users/olebedev/.atom/packages/go-debug/node_modules/react-for-atom/node_modules/react/lib/ReactEventListener.js:93:24)
    at handleTopLevelImpl (/Users/olebedev/.atom/packages/go-debug/node_modules/react-for-atom/node_modules/react/lib/ReactEventListener.js:73:3)
    at ReactDefaultBatchingStrategyTransaction.Mixin.perform (/Users/olebedev/.atom/packages/go-debug/node_modules/react-for-atom/node_modules/react/lib/Transaction.js:136:20)
    at Object.ReactDefaultBatchingStrategy.batchedUpdates (/Users/olebedev/.atom/packages/go-debug/node_modules/react-for-atom/node_modules/react/lib/ReactDefaultBatchingStrategy.js:62:19)
    at Object.batchedUpdates (/Users/olebedev/.atom/packages/go-debug/node_modules/react-for-atom/node_modules/react/lib/ReactUpdates.js:94:20)
    at ReactEventListener.dispatchEvent (/Users/olebedev/.atom/packages/go-debug/node_modules/react-for-atom/node_modules/react/lib/ReactEventListener.js:204:20)
```

### Commands

```
     -4:08.7.0 terminal-panel:toggle (atom-text-editor.editor.is-focused.vim-mode.normal-mode)
  3x -4:06.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -3:51.4.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -3:38.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  3x -2:47.2.0 terminal-panel:toggle (div.panel.cli-status.panel-bottom)
     -2:17.6.0 core:copy (div.panel.cli-status.panel-bottom)
     -1:53.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:43 core:paste (atom-text-editor.editor.mini.is-focused)
     -0:42.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "atom-terminal-panel"
    ],
    "projectHome": "$GOPATH/src",
    "themes": [
      "one-dark-ui",
      "gruvbox"
    ]
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-go, v1.0.6
builder-go, v1.0.0
go-config, v1.1.4
go-debug, v0.1.7
go-get, v1.0.3
go-plus, v4.1.0
gofmt, v1.1.6
gometalinter-linter, v1.1.0
gorename, v1.0.2
gruvbox, v1.0.5
linter, v1.11.4
navigator-godef, v1.0.2
terminal-panel, v1.14.1
tester-go, v1.0.4
vim-mode, v0.65.0

# Dev
No dev packages
```

**Comment by lloiser** [comment]
Did you clicked a command in the panel while having no file open?

**Comment by olebedev** [comment]
@lloiser yeah, It seems that it crashes on non-golang files/tabs. With golang files it works well. Thanks!

**Comment by lloiser** [comment]
Crashing is not expected so I will leave this open and fix it.

> non-golang files/tabs

Like atom settings or other source files (javascript, python, ...)?

**Comment by olebedev** [comment]
The atom settings was opened.
