### ISSUE TITLE
Uncaught TypeError: Cannot read property 'webkitMatchesSelector' of undefined

### ISSUE THREAD

**Issue by Rhaseven7h** [lloiser/go-debug#19]
[Enter steps to reproduce below:]

1. Close all files
2. Start a debugging session

A configuration file specifying package to debug would be more intuitive.

**Atom Version**: 1.7.2
**System**: Mac OS X 10.11.4
**Thrown From**: [go-debug](https://github.com/lloiser/go-debug) package, v0.1.7

### Stack Trace

Uncaught TypeError: Cannot read property 'webkitMatchesSelector' of undefined

```
At /Users/gmedina/.atom/packages/go-debug/node_modules/react-for-atom/node_modules/react/lib/ReactErrorUtils.js:53

TypeError: Cannot read property 'webkitMatchesSelector' of undefined
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:244:26)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
    at Panel.onCommandClick (/Users/gmedina/.atom/packages/go-debug/lib/panel.jsx:285:18)
    at Object.invokeGuardedCallback (/Users/gmedina/.atom/packages/go-debug/node_modules/react-for-atom/node_modules/react/lib/ReactErrorUtils.js:27:12)
    at executeDispatch (/Users/gmedina/.atom/packages/go-debug/node_modules/react-for-atom/node_modules/react/lib/EventPluginUtils.js:79:21)
    at Object.executeDispatchesInOrder (/Users/gmedina/.atom/packages/go-debug/node_modules/react-for-atom/node_modules/react/lib/EventPluginUtils.js:102:5)
    at executeDispatchesAndRelease (/Users/gmedina/.atom/packages/go-debug/node_modules/react-for-atom/node_modules/react/lib/EventPluginHub.js:43:22)
    at executeDispatchesAndReleaseTopLevel (/Users/gmedina/.atom/packages/go-debug/node_modules/react-for-atom/node_modules/react/lib/EventPluginHub.js:54:10)
    at Array.forEach (native)
    at forEachAccumulated (/Users/gmedina/.atom/packages/go-debug/node_modules/react-for-atom/node_modules/react/lib/forEachAccumulated.js:23:9)
    at Object.EventPluginHub.processEventQueue (/Users/gmedina/.atom/packages/go-debug/node_modules/react-for-atom/node_modules/react/lib/EventPluginHub.js:259:7)
    at runEventQueueInBatch (/Users/gmedina/.atom/packages/go-debug/node_modules/react-for-atom/node_modules/react/lib/ReactEventEmitterMixin.js:18:18)
    at Object.ReactEventEmitterMixin.handleTopLevel [as _handleTopLevel] (/Users/gmedina/.atom/packages/go-debug/node_modules/react-for-atom/node_modules/react/lib/ReactEventEmitterMixin.js:34:5)
    at handleTopLevelWithoutPath (/Users/gmedina/.atom/packages/go-debug/node_modules/react-for-atom/node_modules/react/lib/ReactEventListener.js:93:24)
    at handleTopLevelImpl (/Users/gmedina/.atom/packages/go-debug/node_modules/react-for-atom/node_modules/react/lib/ReactEventListener.js:73:3)
    at ReactDefaultBatchingStrategyTransaction.Mixin.perform (/Users/gmedina/.atom/packages/go-debug/node_modules/react-for-atom/node_modules/react/lib/Transaction.js:136:20)
    at Object.ReactDefaultBatchingStrategy.batchedUpdates (/Users/gmedina/.atom/packages/go-debug/node_modules/react-for-atom/node_modules/react/lib/ReactDefaultBatchingStrategy.js:62:19)
    at Object.batchedUpdates (/Users/gmedina/.atom/packages/go-debug/node_modules/react-for-atom/node_modules/react/lib/ReactUpdates.js:94:20)
    at ReactEventListener.dispatchEvent (/Users/gmedina/.atom/packages/go-debug/node_modules/react-for-atom/node_modules/react/lib/ReactEventListener.js:204:20)
```

### Commands

```
     -7:39 go-debug:togglePanel (atom-text-editor.editor.is-focused)
     -7:36.7.0 go-debug:stop (atom-text-editor.editor)
     -7:35.8.0 go-debug:runPackage (atom-text-editor.editor)
     -7:30.9.0 go-debug:stop (atom-text-editor.editor)
     -7:29.8.0 go-debug:runPackage (atom-text-editor.editor)
     -7:23.7.0 go-debug:continue (atom-text-editor.editor)
  4x -7:19.2.0 go-debug:next (atom-text-editor.editor)
     -7:04.2.0 go-debug:stop (atom-text-editor.editor)
     -7:02.4.0 core:save (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -7:00.7.0 go-debug:runPackage (atom-text-editor.editor)
     -6:57.2.0 go-debug:continue (atom-text-editor.editor)
 38x -6:51.8.0 go-debug:next (atom-text-editor.editor)
  3x -3:22.4.0 go-debug:continue (atom-text-editor.editor)
     -0:55.4.0 go-debug:stop (atom-text-editor.editor)
  6x -0:19.9.0 core:close (atom-text-editor.editor.is-focused)
  2x -7:42.8.0 go-debug:runPackage (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
autocomplete-go, v1.0.6
builder-go, v1.0.0
environment, v1.2.0
go-config, v1.1.4
go-debug, v0.1.7
go-get, v1.0.3
go-plus, v4.1.0
gofmt, v1.1.6
gometalinter-linter, v1.1.0
gorename, v1.0.2
linter, v1.11.4
navigator-godef, v1.0.3
pretty-json, v1.0.3
tester-go, v1.0.4

# Dev
No dev packages
```

**Comment by lloiser** [comment]
see #18
