### ISSUE TITLE
The pane toggle command throws Uncaught TypeError: Cannot read property 'dispatch' of undefined

### ISSUE THREAD

**Issue by Coccodrillo** [lloiser/go-debug#20]
1. When pressing cmd+k, cmd+g

**Atom Version**: 1.7.2
**System**: Mac OS X 10.11.3
**Thrown From**: [go-debug](https://github.com/lloiser/go-debug) package, v0.1.8

### Stack Trace

Uncaught TypeError: Cannot read property 'dispatch' of undefined

```
At /Users/rokche/.atom/packages/go-debug/lib/commands.js:63

TypeError: Cannot read property 'dispatch' of undefined
    at atom-workspace.action (/Users/rokche/.atom/packages/go-debug/lib/commands.js:63:28)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -0:09.2.0 find-and-replace:find-previous (atom-text-editor.editor.mini.is-focused)
     -0:06.1.0 core:cancel (div.panels)
     -0:01.0 go-debug:toggle-panel (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "disabledPackages": [
      "angularjs",
      "angularjs-helper",
      "angularjs-snippets"
    ],
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store"
    ],
    "themes": [
      "atom-dark-ui",
      "monokai"
    ]
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-go, v1.0.6
autocomplete-paths, v1.0.2
bootstrap-3-snippetset, v0.0.6
bootstrap3-snippets, v0.1.2
builder-go, v1.0.0
emmet, v2.4.3
go-config, v1.1.4
go-debug, v0.1.8
go-get, v1.0.3
go-plus, v4.1.0
go-quick-import, v0.2.0
go-signature-statusbar, v1.0.2
godoc, v0.2.0
gofmt, v1.1.6
gometalinter-linter, v1.1.0
gorename, v1.0.2
gotests, v0.2.5
linter, v1.11.4
linter-golint, v0.3.0
linter-golinter, v1.2.0
linter-gotype, v0.1.0
linter-govet, v0.1.5
minimap, v4.22.1
monokai, v0.18.0
navigator-godef, v1.0.3
remote-sync, v4.0.1
robin-language-php, v0.9.0
tester-go, v1.0.4

# Dev
No dev packages
```

**Comment by lloiser** [comment]
fixed in b1f0607bff615db61c7f3a23fb374b1e7fcbffe1

**Comment by olebedev** [comment]
Got the same issue.

**Comment by lloiser** [comment]
do you have the most recent version (0.1.11)?

**Comment by olebedev** [comment]
Sure - https://infinit.io/_/RBHUTE4.png

**Comment by lloiser** [comment]
you still have 0.1.8... you have to click the update button...

**Comment by olebedev** [comment]
Oops, you right. Update solves the problem, thanks.
