### ISSUE TITLE
Uncaught Error: The given gutter cannot be removed because it is not within this GutterContainer.

### ISSUE THREAD

**Issue by Rhaseven7h** [lloiser/go-debug#21]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.7.2
**System**: Mac OS X 10.11.4
**Thrown From**: [go-debug](https://github.com/lloiser/go-debug) package, v0.1.8
### Stack Trace

Uncaught Error: The given gutter cannot be removed because it is not within this GutterContainer.

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/gutter-container.js:100

Error: The given gutter cannot be removed because it is not within this GutterContainer.
    at GutterContainer.module.exports.GutterContainer.removeGutter (/Applications/Atom.app/Contents/Resources/app.asar/src/gutter-container.js:100:15)
    at Gutter.module.exports.Gutter.destroy (/Applications/Atom.app/Contents/Resources/app.asar/src/gutter.js:27:30)
    at destroyEditor (/Users/gmedina/.atom/packages/go-debug/lib/editors.js:192:16)
    at onWillDestroyPaneItem (/Users/gmedina/.atom/packages/go-debug/lib/editors.js:37:3)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at PaneContainer.module.exports.PaneContainer.willDestroyPaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:298:27)
    at Pane.module.exports.Pane.destroyItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:630:17)
    at Pane.module.exports.Pane.destroyActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:617:12)
    at Workspace.module.exports.Workspace.destroyActivePaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:692:35)
    at Workspace.module.exports.Workspace.closeActivePaneItemOrEmptyPaneOrWindow (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:731:21)
    at atom-workspace.commandRegistry.add.core:close (/Applications/Atom.app/Contents/Resources/app.asar/src/register-default-commands.js:211:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```
### Commands

```
  2x -0:07.9.0 core:close (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
autocomplete-go, v1.0.6
build, v0.59.0
build-make, v0.8.0
builder-go, v1.0.0
environment, v1.2.0
go-config, v1.1.4
go-debug, v0.1.8
go-get, v1.0.3
go-plus, v4.1.0
gofmt, v1.1.6
gometalinter-linter, v1.1.0
gorename, v1.0.2
linter, v1.11.4
navigator-godef, v1.0.3
pretty-json, v1.0.3
tester-go, v1.0.4

# Dev
No dev packages
```

**Comment by lloiser** [comment]
Any steps on how to reproduce this error?

**Comment by britannic** [comment]
Once this error is thrown, it isn't possible to close the current file tab without restarting Atom.

**Comment by lloiser** [comment]
Still not able to reproduce it but it should not break atom anymore.

**Comment by lloiser** [comment]
This appears to be fixed. Please reopen or report another bug if it happens again.
