### ISSUE TITLE
Uncaught TypeError: validateEventDispatches is not a function

### ISSUE THREAD

**Issue by remysaissy** [lloiser/go-debug#32]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.5
**Thrown From**: [go-debug](https://github.com/lloiser/go-debug) package, v0.1.12

### Stack Trace

Uncaught TypeError: validateEventDispatches is not a function

```
At /Users/r.saissy/.atom/packages/go-debug/node_modules/react-for-atom/node_modules/react/lib/EventPluginUtils.js:99

TypeError: validateEventDispatches is not a function
    at Object.executeDispatchesInOrder (/Users/r.saissy/.atom/packages/go-debug/node_modules/react-for-atom/node_modules/react/lib/EventPluginUtils.js:99:5)
    at executeDispatchesAndRelease (/Users/r.saissy/.atom/packages/go-debug/node_modules/react-for-atom/node_modules/react/lib/EventPluginHub.js:42:22)
    at executeDispatchesAndReleaseTopLevel (/Users/r.saissy/.atom/packages/go-debug/node_modules/react-for-atom/node_modules/react/lib/EventPluginHub.js:53:10)
    at Array.forEach (native)
    at forEachAccumulated (/Users/r.saissy/.atom/packages/go-debug/node_modules/react-for-atom/node_modules/react/lib/forEachAccumulated.js:24:9)
    at Object.EventPluginHub.processEventQueue (/Users/r.saissy/.atom/packages/go-debug/node_modules/react-for-atom/node_modules/react/lib/EventPluginHub.js:215:7)
    at runEventQueueInBatch (/Users/r.saissy/.atom/packages/go-debug/node_modules/react-for-atom/node_modules/react/lib/ReactEventEmitterMixin.js:18:18)
    at Object.ReactEventEmitterMixin.handleTopLevel [as _handleTopLevel] (/Users/r.saissy/.atom/packages/go-debug/node_modules/react-for-atom/node_modules/react/lib/ReactEventEmitterMixin.js:29:5)
    at handleTopLevelImpl (/Users/r.saissy/.atom/packages/go-debug/node_modules/react-for-atom/node_modules/react/lib/ReactEventListener.js:73:24)
    at ReactDefaultBatchingStrategyTransaction.Mixin.perform (/Users/r.saissy/.atom/packages/go-debug/node_modules/react-for-atom/node_modules/react/lib/Transaction.js:136:20)
    at Object.ReactDefaultBatchingStrategy.batchedUpdates (/Users/r.saissy/.atom/packages/go-debug/node_modules/react-for-atom/node_modules/react/lib/ReactDefaultBatchingStrategy.js:63:19)
    at Object.batchedUpdates (/Users/r.saissy/.atom/packages/go-debug/node_modules/react-for-atom/node_modules/react/lib/ReactUpdates.js:97:20)
    at ReactEventListener.dispatchEvent (/Users/r.saissy/.atom/packages/go-debug/node_modules/react-for-atom/node_modules/react/lib/ReactEventListener.js:150:20)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "disabledPackages": [
      "linter-rubocop",
      "linter-foodcritic"
    ],
    "projectHome": "/Users/remy/Projects/criteo"
  },
  "go-debug": {
    "panelInitialVisible": false
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-go, v1.1.0
builder-go, v1.0.0
formatter-gofmt, v1.0.1
go-config, v1.1.4
go-debug, v0.1.12
go-get, v1.0.3
go-plus, v4.1.0
gofmt, v1.1.6
gometalinter-linter, v1.1.0
gorename, v1.0.2
language-chef, v0.9.0
latexer, v0.3.0
latextools, v0.8.1
linter, v1.11.4
linter-chktex, v1.3.0
linter-golinter, v1.2.0
navigator-godef, v1.0.3
tester-go, v1.0.4

# Dev
No dev packages
```

**Comment by lloiser** [comment]
seems to be fixed with the new react version! (a4e227bc692114afec8a1881f99535f3c541e94e)
