### ISSUE TITLE
Uncaught Error: Cannot decorate a destroyed marker

### ISSUE THREAD

**Issue by iu0v1** [lloiser/go-debug#48]
[Enter steps to reproduce below:]

1. Install.
2. Make any action.

**Atom Version**: 1.9.9
**System**: Unknown Windows Version
**Thrown From**: [go-debug](https://github.com/lloiser/go-debug) package, v0.1.19

### Stack Trace

Uncaught Error: Cannot decorate a destroyed marker

```
At C:\Users\lord\AppData\Local\atom\app-1.9.9\resources\app.asar\src\decoration-manager.js:192

Error: Cannot decorate a destroyed marker
    at DecorationManager.module.exports.DecorationManager.decorateMarker (C:\Users\lord\AppData\Local\atom\app-1.9.9\resources\app.asar\src\decoration-manager.js:192:15)
    at TextEditor.module.exports.TextEditor.decorateMarker (C:\Users\lord\AppData\Local\atom\app-1.9.9\resources\app.asar\src\text-editor.js:1540:37)
    at GutterContainer.module.exports.GutterContainer.addGutterDecoration (C:\Users\lord\AppData\Local\atom\app-1.9.9\resources\app.asar\src\gutter-container.js:111:30)
    at Gutter.module.exports.Gutter.decorateMarker (C:\Users\lord\AppData\Local\atom\app-1.9.9\resources\app.asar\src\gutter.js:70:35)
    at updateMarker (C:/Users/lord/.atom/packages/go-debug/lib/editors.js:131:33)
    at C:/Users/lord/.atom/packages/go-debug/lib/editors.js:80:23
    at Array.forEach (native)
    at updateMarkers (C:/Users/lord/.atom/packages/go-debug/lib/editors.js:80:7)
    at Array.<anonymous> (C:/Users/lord/.atom/packages/go-debug/lib/editors.js:161:3)
    at C:/Users/lord/.atom/packages/go-debug/lib/utils.js:44:12
```

### Commands

```
 13x -1:19.3.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-always.seti-ui-no-icons.theme-monokai-syntax-for-one-dark.theme-one-dark-ui)
  2x -0:36.1.0 go-debug:toggle-breakpoint (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "allowPendingPaneItems": false,
    "audioBeep": false,
    "automaticallyUpdate": false,
    "closeEmptyWindows": false,
    "disabledPackages": [
      "metrics",
      "spell-check"
    ],
    "openEmptyEditorOnStart": false,
    "packagesWithKeymapsDisabled": [],
    "themes": [
      "one-dark-ui",
      "monokai-syntax-for-one-dark"
    ]
  },
  "go-debug": {
    "limitCommandsToGo": true
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-go, v1.1.1 (active)
builder-go, v1.0.1 (active)
environment, v1.2.0 (active)
file-icons, v1.7.18 (active)
git-control, v0.8.2 (inactive)
git-diff-popup, v0.1.8 (inactive)
git-time-machine, v1.5.3 (inactive)
go-config, v1.2.3 (active)
go-debug, v0.1.19 (active)
go-get, v1.0.4 (active)
go-plus, v4.2.0 (active)
godoc, v0.3.0 (active)
gofmt, v1.1.7 (active)
gometalinter-linter, v1.1.1 (active)
gorename, v1.0.3 (active)
highlight-line, v0.11.1 (active)
indent-guide-ext, v0.2.1 (active)
indent-guide-improved, v1.4.9 (active)
linter, v1.11.16 (active)
linter-jshint, v2.1.0 (active)
markdown-format, v2.5.1 (active)
minimap, v4.24.7 (active)
minimap-codeglance, v0.4.5 (active)
minimap-cursorline, v0.2.0 (active)
minimap-linter, v1.1.1 (active)
monokai-syntax-for-one-dark, v0.2.2 (active)
navigator-godef, v1.0.4 (active)
project-ring, v0.39.0 (active)
synced-sidebar, v0.4.3 (active)
tabs-to-spaces, v1.0.2 (active)
tester-go, v1.0.5 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.51.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.43.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.3.2 (active)
one-light-ui, v1.3.2 (inactive)
one-dark-syntax, v1.2.0 (inactive)
one-light-syntax, v1.2.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.2 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.0 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.0 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.39.0 (active)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
find-and-replace, v0.198.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.1 (active)
metrics, v0.53.1 (inactive)
notifications, v0.64.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.238.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (inactive)
status-bar, v1.4.1 (active)
styleguide, v0.47.1 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.98.1 (active)
timecop, v0.33.1 (active)
tree-view, v0.208.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.32.2 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.0 (active)
language-csharp, v0.12.1 (active)
language-css, v0.36.2 (active)
language-gfm, v0.86.0 (active)
language-git, v0.13.0 (active)
language-go, v0.42.0 (active)
language-html, v0.44.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.22.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.0 (active)
language-less, v0.29.3 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.0 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.68.5 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.52.0 (active)
language-shellscript, v0.22.3 (active)
language-source, v0.9.0 (active)
language-sql, v0.21.1 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.8 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by lloiser** [comment]
> 1. Install.
> 2. Make any action.

hmm not a lot of information... I can see that you tried to toggle a breakpoint.
Anything else you did before? E.g. moving /removing larger code blocks near/around the breakpoint, moving/replacing files the breakpoint has been part of, ... stuff like that

**Comment by Dhar** [comment]
[Enter steps to reproduce:]

1. Open any Go source file
2. F9 to set breakpoint

**Atom**: 1.43.0 x64
**Electron**: 4.2.7
**OS**: Pop!_OS 19.10
**Thrown From**: [go-debug](https://github.com/lloiser/go-debug) package 1.7.0


### Stack Trace

Uncaught Error: Cannot decorate a destroyed marker

```
At /usr/share/atom/resources/app/static/<embedded>:11

Error: Cannot decorate a destroyed marker
    at DecorationManager.decorateMarker (/usr/share/atom/resources/app/static/<embedded>:11:519246)
    at TextEditor.decorateMarker (/usr/share/atom/resources/app/static/<embedded>:11:27540)
    at GutterContainer.addGutterDecoration (/usr/share/atom/resources/app/static/<embedded>:11:565340)
    at Gutter.decorateMarker (/usr/share/atom/resources/app/static/<embedded>:14:129839)
    at Editor.updateMarker (/packages/go-debug/lib/editor.js:79:34)
    at /packages/go-debug/lib/editor.js:59:30
    at Array.forEach (<anonymous>)
    at Editor.updateMarkers (/packages/go-debug/lib/editor.js:59:9)
    at /packages/go-debug/lib/editor-manager.js:41:9
    at Map.forEach (<anonymous>)
    at EditorManager.handleStoreChange (/packages/go-debug/lib/editor-manager.js:39:19)
    at /packages/go-debug/lib/utils.js:56:12
```

### Commands

```
     -4:32.9.0 debugger:show (atom-workspace.workspace.scrollbars-visible-always.theme-solarized-light-syntax.theme-one-light-ui)
     -3:45.1.0 settings-view:open (ul.list-inline.tab-bar.inset-panel)
     -3:31.2.0 go-debug:toggle-breakpoint (input.hidden-input)
  3x -3:09.0 go-debug:next (button.btn.go-debug-btn-flat)
  3x -1:06.2.0 go-debug:toggle-breakpoint (input.hidden-input)
     -1:02.1.0 go-debug:resume (button.btn.go-debug-btn-flat)
     -1:00.7.0 go-debug:toggle-breakpoint (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-ide-debugger-python 0.7.3 
atom-ide-ui 0.13.0 
atom-jinja2 0.6.0 
autocomplete-python 1.16.0 
busy-signal 2.0.1 
column-select 1.0.1 
file-icons 2.1.39 
go-debug 1.7.0 
go-plus 6.1.0 
go-signature-statusbar 1.2.3 
ide-python 1.5.0 
ide-yaml 0.6.0 
intentions 1.1.5 
kite 0.178.0 
language-docker 1.1.8 
language-elixir 0.23.0 
language-jenkinsfile 0.1.1 
language-terraform 0.8.1 
linter 2.3.1 
linter-docker 0.3.2 
linter-dryer 0.4.1 
linter-flake8 2.4.0 
linter-js-yaml 1.4.6 
linter-mypy 2.6.9 
linter-pylint 2.1.1 
linter-terraform-syntax 1.4.0 
linter-ui-default 1.8.1 
minimap 4.29.9 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-lens 0.3.0 
minimap-linter 2.2.1 
minimap-pigments 0.2.2 
python-black 0.7.0 
python-indent 1.2.5 
python-tools 0.6.9 
selection-highlight 0.1.6 
Sublime-Style-Column-Selection 1.7.5 
terraform-fmt 0.3.0 
textmate-zenburn-syntax 0.2.0 
yaml-path 0.1.1 
zenburn 3.1.0 
zenburn-plus-syntax 0.1.0 
zenburn-plus-ui 0.2.1 
zenburn-syntax 3.1.2 
zenburn-theme 1.3.0 
zenburn-ui 0.2.1 
```

**Comment by Dhar** [comment]
This is definitely an interaction with the `minimap-lens 0.3.0` add-on.  When I disable minimap-lens, the issue goes away.  When I enable it, this error occurs.
