### ISSUE TITLE
Debugging is not working as expected

### ISSUE THREAD

**Issue by pavel-odintsov** [lloiser/go-debug#51]
Hello!

First of all, THANKS for your project! :) It's awesome! 

But I have some issue with it.

I have been playing with Delve for some time at my Mac El Capitan from CLI and it's working great!

I'm using it this way:
- Run debugger with command: dlv debug  ../mytool -- -config /tmp/tmpoG4xmF_internal
- Setup breakpoint: b file.go:138
- continue
- Hit breakpoint with custom tool 

And at this step I could look around, check traces, values of variables and everything what I want.

But when I'm trying to reproduce same approach it with Atom Go I'm going into troubles :(

I could run debugging session, I could set break points.

But when I hit breakpointed code I got:

```
Delve output: 2016/08/22 18:29:57 debugger.go:271: switching to goroutine 74
```

But I see no changes in variables / goroutines field: 
<img width="213" alt="atom go debug" src="https://cloud.githubusercontent.com/assets/2744166/17860606/95da65fc-6896-11e6-9a83-c1ddbf94e10f.png">

Also I see no changes about "current instruction processed by debugger" inside editor.

What I'm going wrong?

**Comment by lloiser** [comment]
Nothing else is in the `Output panel`? 
Then open the developer tools in atom using `alt-cmd-i` and check if there are any errors in the `Console` tab.

**Comment by pavel-odintsov** [comment]
Hello!

Nothing else in Output panel :( I also checked Atom's console but have no luck here too.

I tried to reproduce all steps with dlv's CLI and it works perfectly:
```
dlv debug --log=true -- -config /tmp/option
b corelogic.go:127
continue
```

And got following:
```
>......corelogic.go:127 (hits goroutine(92):1 total:1)

=> 127:		data, err := GetQuery(r)
   128:		if err != nil {
   129:			return
   130:		}
   131:		if data == nil {
(dlv) exit
```

**Comment by pavel-odintsov** [comment]
But after some time (1-2 minutes) after "switching to goroutine 74" (dlv hit my breakpoint) I saw following:
```
Delve output: panic: runtime error: makeslice: len out of range
goroutine 10 [running]:
panic(0x4621860, 0xc821256e60)
 /usr/local/Cellar/go/1.6.2/libexec/src/runtime/panic.go:481 +0x3e6
github.com/derekparker/delve/proc.(*Thread).readMemory(0xc82174e370, 0xc82008e000, 0xfffffffffffffff0, 0x0, 0x0, 0x0, 0x0, 0x0)
 /private/tmp/delve-20160822-31823-fs8eh2/delve-0.11.0-alpha/src/github.com/derekparker/delve/proc/threads_darwin.go:112 +0x9c
github.com/derekparker/delve/proc.cacheMemory(0x5b0b380, 0xc8216326f0, 0xc82008e000, 0xfffffffffffffff0, 0x0, 0x0)
 /private/tmp/delve-20160822-31823-fs8eh2/delve-0.11.0-alpha/src/github.com/derekparker/delve/proc/mem.go:42 +0xf2
Delve output: github.com/derekparker/delve/proc.(*Variable).loadArrayValues(0xc821401420, 0x0)
 /private/tmp/delve-20160822-31823-fs8eh2/delve-0.11.0-alpha/src/github.com/derekparker/delve/proc/variables.go:938 +0xa6
github.com/derekparker/delve/proc.(*Variable).loadValueInternal(0xc821401420, 0x0)
 /private/tmp/delve-20160822-31823-fs8eh2/delve-0.11.0-alpha/src/github.com/derekparker/delve/proc/variables.go:744 +0x939
github.com/derekparker/delve/proc.(*Variable).loadValue(0xc821401420)
 /private/tmp/delve-20160822-31823-fs8eh2/delve-0.11.0-alpha/src/github.com/derekparker/delve/proc/variables.go:710 +0x2a
github.com/derekparker/delve/proc.(*EvalScope).extractVariableFromEntry(0xc821353810, 0xc821632450, 0x0, 0x0, 0x0)
 /private/tmp/delve-20160822-31823-fs8eh2/delve-0.11.0-alpha/src/github.com/derekparker/delve/proc/variables.go:499 +0x98
github.com/derekparker/delve/proc.(*EvalScope).variablesByTag(0xc821353810, 0x34, 0x0, 0x0, 0x0, 0x0, 0x0)
 /private/tmp/delve-20160822-31823-fs8eh2/delve-0.11.0-alpha/src/github.com/derekparker/delve/proc/variables.go:1484 +0x174
github.com/derekparker/delve/proc.(*EvalScope).LocalVariables(0xc821353810, 0x0, 0x0, 0x0, 0x0, 0x0)
 /private/tmp/delve-20160822-31823-fs8eh2/delve-0.11.0-alpha/src/github.com/derekparker/delve/proc/variables.go:530 +0x46
github.com/derekparker/delve/service/debugger.(*Debugger).convertStacktrace(0xc82005fcc0, 0xc821228000, 0x4, 0x15, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
 /private/tmp/delve-20160822-31823-fs8eh2/delve-0.11.0-alpha/src/github.com/derekparker/delve/service/debugger/debugger.go:521 +0x30e
github.com/derekparker/delve/service/debugger.(*Debugger).Stacktrace(0xc82005fcc0, 0x5b, 0x14, 0x44e6501, 0x0, 0x0, 0x0, 0x0, 0x0)
 /private/tmp/delve-20160822-31823-fs8eh2/delve-0.11.0-alpha/src/github.com/derekparker/delve/service/debugger/debugger.go:511 +0x188
github.com/derekparker/delve/service/rpc.(*RPCServer).StacktraceGoroutine(0xc8200dfa60, 0xc8203cb280, 0xc8203cb2e0, 0x0, 0x0)
 /private/tmp/delve-20160822-31823-fs8eh2/delve-0.11.0-alpha/src/github.com/derekparker/delve/service/rpc/server.go:120 +0x5d
reflect.Value.call(0x45cdca0, 0x46c5e28, 0x13, 0x46e54f8, 0x4, 0xc821353ed8, 0x3, 0x3, 0x0, 0x0, ...)
 /usr/local/Cellar/go/1.6.2/libexec/src/reflect/value.go:435 +0x120d
reflect.Value.Call(0x45cdca0, 0x46c5e28, 0x13, 0xc821353ed8, 0x3, 0x3, 0x0, 0x0, 0x0)
 /usr/local/Cellar/go/1.6.2/libexec/src/reflect/value.go:303 +0xb1
net/rpc.(*service).call(0xc82173c040, 0xc82173c000, 0xc82173e088, 0xc8217a6c80, 0xc8212bc0a0, 0x44eb600, 0xc8203cb280, 0x16, 0x44e6500, 0xc8203cb2e0, ...)
 /usr/local/Cellar/go/1.6.2/libexec/src/net/rpc/server.go:383 +0x1c2
created by net/rpc.(*Server).ServeCodec
 /usr/local/Cellar/go/1.6.2/libexec/src/net/rpc/server.go:477 +0x49d
delve closed with code 2
```

So this issue could be related with Delve's RPC API! I'm going to report issue to Delve authors!

**Comment by lloiser** [comment]
This appears to be fixed in delve in the meanwhile. Please update delve (https://github.com/derekparker/delve/tree/master/Documentation/installation).

Please reopen or report another bug if it happens again.
