### ISSUE TITLE
Uncaught Error: watch ~/golang/src/packagename ENOSPC

### ISSUE THREAD

**Issue by wilbiga** [lloiser/go-debug#73]
[Enter steps to reproduce below:]

1. open atom and this error pop up in the top right corner

**Atom Version**: 1.13.1
**Electron Version**: 1.3.13
**System**: Linux Mint
**Thrown From**: [go-debug](https://github.com/lloiser/go-debug) package, v1.0.4

### Stack Trace

Uncaught Error: watch /home/user/golang/src/packagename ENOSPC

```
At events.js:160

Error: watch /home/user/golang/src/packagename ENOSPC
    at exports._errnoException (util.js:1026:11)
    at FSWatcher.start (fs.js:1439:19)
    at Object.fs.watch (fs.js:1466:11)
    at createFsWatchInstance (/home/user/.atom/packages/go-debug/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/home/user/.atom/packages/go-debug/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/user/.atom/packages/go-debug/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at FSWatcher.NodeFsHandler._handleDir (/home/user/.atom/packages/go-debug/node_modules/chokidar/lib/nodefs-handler.js:407:19)
    at FSWatcher.<anonymous> (/home/user/.atom/packages/go-debug/node_modules/chokidar/lib/nodefs-handler.js:455:19)
    at FSWatcher.<anonymous> (/home/user/.atom/packages/go-debug/node_modules/chokidar/lib/nodefs-handler.js:460:16)
    at FSReqWrap.oncomplete (fs.js:123:15)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "telemetryConsent": "limited"
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.29.17 (inactive)
atom-react-autocomplete, v0.1.10 (active)
atom-react-native-autocomplete, v0.0.27 (active)
atom-react-native-css, v1.1.3 (active)
atom-react-preview, v2.0.0 (active)
go-debug, v1.0.4 (active)
go-plus, v5.1.1 (active)
go-signature-statusbar, v1.2.0 (active)
hyperclick, v0.0.40 (active)
language-javascript-jsx, v0.3.7 (active)
language-log, v1.8.0 (active)
language-mako, v0.6.0 (active)
language-riot-tag, v0.2.2 (active)
linter, v1.11.21 (active)
react, v0.16.2 (active)
react-es6-snippets, v0.3.0 (active)
react-native-snippets, v0.3.0 (active)
react-snippets, v0.6.2 (active)
atom-dark-syntax, v0.28.0 (inactive)
atom-dark-ui, v0.53.0 (inactive)
atom-light-syntax, v0.29.0 (inactive)
atom-light-ui, v0.46.0 (inactive)
base16-tomorrow-dark-theme, v1.4.0 (inactive)
base16-tomorrow-light-theme, v1.4.0 (inactive)
one-dark-ui, v1.8.2 (active)
one-light-ui, v1.8.2 (inactive)
one-dark-syntax, v1.6.0 (active)
one-light-syntax, v1.6.0 (inactive)
solarized-dark-syntax, v1.1.1 (inactive)
solarized-light-syntax, v1.1.1 (inactive)
about, v1.7.2 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.14.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.33.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.29.0 (inactive)
autosave, v0.23.2 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.43.2 (active)
bracket-matcher, v0.85.1 (active)
command-palette, v0.39.1 (inactive)
deprecation-cop, v0.55.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.204.5 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.2.0 (active)
go-to-line, v0.31.2 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.1 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.159.3 (active)
metrics, v1.1.3 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.2 (inactive)
settings-view, v0.244.0 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.5 (active)
status-bar, v1.6.0 (active)
styleguide, v0.48.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.1 (active)
timecop, v0.33.2 (active)
tree-view, v0.211.1 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.39.0 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.1 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by lloiser** [comment]
`ENOSPC` is a really interesting error. It either means `Error NO SPaCe`, so your disk is full. Or that the folder being watched has too many files/folders in it.

* Did you add something in the `Configuration File` setting of go-debug?
* What's this `/home/user/golang/src/packagename` folder that is mentioned in the log? Is it the folder you opened in atom?

**Comment by wilbiga** [comment]
I have enough disk space:

user@user-pc ~ $ df -h
File system     Dim.  Used  Avail. Usage% Mount
/dev/sda5        72G   41G     28G  60%    /

I dont have a Configuration File. 
![schermata del 2017-02-03 18-04-47](https://cloud.githubusercontent.com/assets/12687676/22600550/55b007a8-ea3b-11e6-9ed9-877bbe425fa4.png)

This:
/home/user/golang/src/packagename

is the folder i opened in atom. It happen if i open any folder

**Comment by wilbiga** [comment]
I solved this issue.

In the screenshot above there are 2 error. The first one is pointing to this documentation:

https://github.com/atom/atom/blob/master/docs/build-instructions/linux.md#typeerror-unable-to-watch-path

I follow the solution but was working only the temporary one.

I am on Debian so i had to use this line to make it permanent:

echo fs.inotify.max_user_watches=32768 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p

Now i can open atom without error.

Thank you.
