### ISSUE TITLE
Delve output: unexpected fault address 0x0

### ISSUE THREAD

**Issue by djahma** [lloiser/go-debug#77]
Hi,
Don't what happened since it was working fine, I did not update anything, and suddenly it all broke with the message below. I tried to uninstall, restart atom, install again but got same. I'm using atom 1.14.3 and go-debug 1.0.4. Hope you could sort that cause I love this plugin! Cheers.

``` Starting delve with config "Debug"
Delve output: unexpected fault address 0x0
fatal error: fault
Delve output: [signal 0xb code=0x80 addr=0x0 pc=0x545934]

goroutine 1 [running]:
runtime.throw(0xb1cce0, 0x5)
	/usr/local/go/src/runtime/panic.go:547 +0x90 fp=0xc8214753b8 sp=0xc8214753a0
runtime.sigpanic()
	/usr/local/go/src/runtime/sigpanic_unix.go:27 +0x2ab fp=0xc821475408 sp=0xc8214753b8
reflect.(*rtype).Name(0x950ba0, 0x1e, 0x9f8ad8)
	/usr/local/go/src/reflect/type.go:562 +0x14 fp=0xc821475410 sp=0xc821475408
github.com/derekparker/delve/service/rpccommon.isExportedOrBuiltinType(0x7f20114d90a8, 0x950ba0, 0x7f20114d90a8)
	/home/gman/Development/Golang/src/github.com/derekparker/delve/service/rpccommon/server.go:171 +0x70 fp=0xc821475440 sp=0xc821475410
github.com/derekparker/delve/service/rpccommon.suitableMethods(0xa4fc60, 0xc82002c020, 0xc821efa7b0)
	/home/gman/Development/Golang/src/github.com/derekparker/delve/service/rpccommon/server.go:203 +0x70a fp=0xc8214758c0 sp=0xc821475440
github.com/derekparker/delve/service/rpccommon.(*ServerImpl).Run(0xc82000b310, 0x0, 0x0)
	/home/gman/Development/Golang/src/github.com/derekparker/delve/service/rpccommon/server.go:128 +0x55a fp=0xc821475980 sp=0xc8214758c0
github.com/derekparker/delve/cmd/dlv/cmds.execute(0x0, 0xc820013ce0, 0x1, 0x1, 0xc82002c0d0, 0x1, 0x0)
	/home/gman/Development/Golang/src/github.com/derekparker/delve/cmd/dlv/cmds/commands.go:406 +0x352 fp=0xc821475b50 sp=0xc821475980
github.com/derekparker/delve/cmd/dlv/cmds.debugCmd.func1(0xc820094c00, 0xc82011eae0, 0x0, 0x3, 0x0)
	/home/gman/Development/Golang/src/github.com/derekparker/delve/cmd/dlv/cmds/commands.go:235 +0x678 fp=0xc821475ca0 sp=0xc821475b50
github.com/derekparker/delve/cmd/dlv/cmds.debugCmd(0xc820094c00, 0xc82011eae0, 0x0, 0x3)
	/home/gman/Development/Golang/src/github.com/derekparker/delve/cmd/dlv/cmds/commands.go:215 +0x3f fp=0xc821475cd0 sp=0xc821475ca0
github.com/derekparker/delve/vendor/github.com/spf13/cobra.(*Command).execute(0xc820094c00, 0xc82011ea50, 0x3, 0x3, 0x0, 0x0)
	/home/gman/Development/Golang/src/github.com/derekparker/delve/vendor/github.com/spf13/cobra/command.go:569 +0x85a fp=0xc821475de8 sp=0xc821475cd0
github.com/derekparker/delve/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc820094600, 0xc820094c00, 0x0, 0x0)
	/home/gman/Development/Golang/src/github.com/derekparker/delve/vendor/github.com/spf13/cobra/command.go:656 +0x55c fp=0xc821475ef8 sp=0xc821475de8
github.com/derekparker/delve/vendor/github.com/spf13/cobra.(*Command).Execute(0xc820094600, 0x0, 0x0)
	/home/gman/Development/Golang/src/github.com/derekparker/delve/vendor/github.com/spf13/cobra/command.go:615 +0x2d fp=0xc821475f20 sp=0xc821475ef8
main.main()
	/home/gman/Development/Golang/src/github.com/derekparker/delve/cmd/dlv/main.go:13 +0x4a fp=0xc821475f40 sp=0xc821475f20
runtime.main()
	/usr/local/go/src/runtime/proc.go:188 +0x2b0 fp=0xc821475f90 sp=0xc821475f40
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc821475f98Delve output:  sp=0xc821475f90

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1

goroutine 5 [syscall]:
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:116 +0x132
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 7 [chan receive, locked to thread]:
github.com/derekparker/delve/proc.(*Process).handlePtraceFuncs(0xc820092600)
	/home/gman/Development/Golang/src/github.com/derekparker/delve/proc/proc.go:780 +0xc3
created by github.com/derekparker/delve/proc.New
	/home/gman/Development/Golang/src/github.com/derekparker/delve/proc/proc.go:87 +0x36d
```

**Comment by lloiser** [comment]
This is most likely a problem with [`delve`](https://github.com/derekparker/delve) (the actual debugger) and not with `go-debug` (the atom plugin).

To make sure please run `dlv debug <go package>` (or `dlv test <go package>` for tests) in your terminal. If it fails there too please open an issue at [`delve`](https://github.com/derekparker/delve).

**Comment by lloiser** [comment]
Beside this please update delve. Maybe this issue has already been resolved with the latest version. https://github.com/derekparker/delve/tree/master/Documentation/installation

**Comment by djahma** [comment]
Thanks for the guidance. dlv wouldn't work in terminal either, I reinstalled it and all is fine again. Cheers
