### ISSUE TITLE
Cannot read property 'Component' of undefined

### ISSUE THREAD

**Issue by sadovnychyi** [lloiser/go-debug#8]
Cannot even initialize the package, found this in logs. I'm on 1.7.0-beta4 version of Atom. OSX.

```
Uncaught (in promise) TypeError: Cannot read property 'Component' of undefined
    at Object.<anonymous> (/Users/sadovnychyi/.atom/packages/go-debug/lib/variables.jsx:64:23)
    at Module._compile (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/sadovnychyi/.atom/packages/go-debug/lib/panel.jsx:25:21)
    at Module._compile (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.start (/Users/sadovnychyi/.atom/packages/go-debug/lib/main.js:60:11)
    at /Users/sadovnychyi/.atom/packages/go-debug/lib/main.js:42:9
    at process._tickCallback (node.js:392:9)
```

Re-running `npm install` manually didn't help.

**Comment by lloiser** [comment]
```
cd /Users/sadovnychyi/.atom/packages/go-debug
npm install
# then restart atom
```
does this help?

**Comment by sadovnychyi** [comment]
I mentioned in an update that re-running npm install manually didn't help. Both react and react-for-atom are in node_modules directory.

**Comment by sadovnychyi** [comment]
Output of `npm ls`:

```~/.atom/packages/go-debug·npm ls
go-debug@0.1.5 /Users/sadovnychyi/.atom/packages/go-debug
├─┬ atom-package-deps@4.0.1
│ └─┬ atom-package-path@1.1.0
│   └── sb-callsite@1.1.2
├─┬ eslint@1.10.3
│ ├─┬ chalk@1.1.3
│ │ ├── ansi-styles@2.2.1
│ │ ├── has-ansi@2.0.0
│ │ ├── strip-ansi@3.0.1
│ │ └── supports-color@2.0.0
│ ├─┬ concat-stream@1.5.1
│ │ ├── inherits@2.0.1
│ │ ├─┬ readable-stream@2.0.6
│ │ │ ├── core-util-is@1.0.2
│ │ │ ├── isarray@1.0.0
│ │ │ ├── process-nextick-args@1.0.6
│ │ │ ├── string_decoder@0.10.31
│ │ │ └── util-deprecate@1.0.2
│ │ └── typedarray@0.0.6
│ ├─┬ debug@2.2.0
│ │ └── ms@0.7.1
│ ├─┬ doctrine@0.7.2
│ │ ├── esutils@1.1.6
│ │ └── isarray@0.0.1
│ ├── escape-string-regexp@1.0.5
│ ├─┬ escope@3.6.0
│ │ ├─┬ es6-map@0.1.3
│ │ │ ├── d@0.1.1
│ │ │ ├── es5-ext@0.10.11
│ │ │ ├── es6-iterator@2.0.0
│ │ │ ├── es6-set@0.1.4
│ │ │ ├── es6-symbol@3.0.2
│ │ │ └── event-emitter@0.3.4
│ │ ├── es6-weak-map@2.0.1
│ │ └─┬ esrecurse@4.1.0
│ │   └── estraverse@4.1.1
│ ├── espree@2.2.5
│ ├── estraverse@4.2.0
│ ├── estraverse-fb@1.3.1
│ ├── esutils@2.0.2
│ ├─┬ file-entry-cache@1.2.4
│ │ └─┬ flat-cache@1.0.10
│ │   ├─┬ del@2.2.0
│ │   │ ├─┬ globby@4.0.0
│ │   │ │ ├─┬ array-union@1.0.1
│ │   │ │ │ └── array-uniq@1.0.2
│ │   │ │ ├── arrify@1.0.1
│ │   │ │ └── glob@6.0.4
│ │   │ ├── is-path-cwd@1.0.0
│ │   │ ├─┬ is-path-in-cwd@1.0.0
│ │   │ │ └── is-path-inside@1.0.0
│ │   │ ├── pify@2.3.0
│ │   │ ├─┬ pinkie-promise@2.0.0
│ │   │ │ └── pinkie@2.0.4
│ │   │ └─┬ rimraf@2.5.2
│ │   │   └── glob@7.0.3
│ │   ├── graceful-fs@4.1.3
│ │   ├── read-json-sync@1.1.1
│ │   └── write@0.2.1
│ ├─┬ glob@5.0.15
│ │ ├─┬ inflight@1.0.4
│ │ │ └── wrappy@1.0.1
│ │ └── once@1.3.3
│ ├── globals@8.18.0
│ ├─┬ handlebars@4.0.5
│ │ ├── async@1.5.2
│ │ ├── optimist@0.6.1
│ │ ├─┬ source-map@0.4.4
│ │ │ └── amdefine@1.0.0
│ │ └─┬ uglify-js@2.6.2
│ │   ├── async@0.2.10
│ │   ├── source-map@0.5.3
│ │   ├── uglify-to-browserify@1.0.2
│ │   └─┬ yargs@3.10.0
│ │     ├── camelcase@1.2.1
│ │     ├─┬ cliui@2.1.0
│ │     │ ├─┬ center-align@0.1.3
│ │     │ │ ├─┬ align-text@0.1.4
│ │     │ │ │ ├─┬ kind-of@3.0.2
│ │     │ │ │ │ └── is-buffer@1.1.3
│ │     │ │ │ ├── longest@1.0.1
│ │     │ │ │ └── repeat-string@1.5.4
│ │     │ │ └── lazy-cache@1.0.3
│ │     │ ├── right-align@0.1.3
│ │     │ └── wordwrap@0.0.2
│ │     ├── decamelize@1.2.0
│ │     └── window-size@0.1.0
│ ├─┬ inquirer@0.11.4
│ │ ├── ansi-escapes@1.3.0
│ │ ├── ansi-regex@2.0.0
│ │ ├─┬ cli-cursor@1.0.2
│ │ │ └─┬ restore-cursor@1.0.1
│ │ │   ├── exit-hook@1.1.1
│ │ │   └── onetime@1.1.0
│ │ ├── cli-width@1.1.1
│ │ ├── figures@1.5.0
│ │ ├── lodash@3.10.1
│ │ ├─┬ readline2@1.0.1
│ │ │ ├─┬ code-point-at@1.0.0
│ │ │ │ └── number-is-nan@1.0.0
│ │ │ ├── is-fullwidth-code-point@1.0.0
│ │ │ └── mute-stream@0.0.5
│ │ ├── run-async@0.1.0
│ │ ├── rx-lite@3.1.2
│ │ ├── string-width@1.0.1
│ │ └── through@2.3.8
│ ├─┬ is-my-json-valid@2.13.1
│ │ ├── generate-function@2.0.0
│ │ ├─┬ generate-object-property@1.2.0
│ │ │ └── is-property@1.0.2
│ │ ├── jsonpointer@2.0.0
│ │ └── xtend@4.0.1
│ ├─┬ is-resolvable@1.0.0
│ │ └── tryit@1.0.2
│ ├─┬ js-yaml@3.4.5
│ │ ├─┬ argparse@1.0.7
│ │ │ └── sprintf-js@1.0.3
│ │ └── esprima@2.7.2
│ ├─┬ json-stable-stringify@1.0.1
│ │ └── jsonify@0.0.0
│ ├─┬ lodash.clonedeep@3.0.2
│ │ ├─┬ lodash._baseclone@3.3.0
│ │ │ ├── lodash._baseassign@3.2.0
│ │ │ └── lodash._basefor@3.0.3
│ │ └── lodash._bindcallback@3.0.1
│ ├─┬ lodash.merge@3.3.2
│ │ ├── lodash._arraycopy@3.0.0
│ │ ├── lodash._arrayeach@3.0.0
│ │ ├─┬ lodash._createassigner@3.1.1
│ │ │ └── lodash._isiterateecall@3.0.9
│ │ ├── lodash._getnative@3.9.1
│ │ ├── lodash.isarguments@3.0.8
│ │ ├── lodash.isarray@3.0.4
│ │ ├── lodash.isplainobject@3.2.0
│ │ ├── lodash.istypedarray@3.0.6
│ │ ├── lodash.keys@3.1.2
│ │ ├── lodash.keysin@3.0.8
│ │ └─┬ lodash.toplainobject@3.0.0
│ │   └── lodash._basecopy@3.0.1
│ ├─┬ lodash.omit@3.1.0
│ │ ├── lodash._arraymap@3.0.0
│ │ ├─┬ lodash._basedifference@3.0.3
│ │ │ ├── lodash._baseindexof@3.1.0
│ │ │ ├── lodash._cacheindexof@3.0.2
│ │ │ └── lodash._createcache@3.1.2
│ │ ├── lodash._baseflatten@3.1.4
│ │ ├── lodash._pickbyarray@3.0.2
│ │ ├── lodash._pickbycallback@3.0.0
│ │ └── lodash.restparam@3.6.1
│ ├─┬ minimatch@3.0.0
│ │ └─┬ brace-expansion@1.1.3
│ │   ├── balanced-match@0.3.0
│ │   └── concat-map@0.0.1
│ ├─┬ mkdirp@0.5.1
│ │ └── minimist@0.0.8
│ ├── object-assign@4.0.1
│ ├─┬ optionator@0.6.0
│ │ ├── deep-is@0.1.3
│ │ ├── fast-levenshtein@1.0.7
│ │ ├── levn@0.2.5
│ │ ├── prelude-ls@1.1.2
│ │ ├── type-check@0.3.2
│ │ └── wordwrap@0.0.3
│ ├── path-is-absolute@1.0.0
│ ├── path-is-inside@1.0.1
│ ├── shelljs@0.5.3
│ ├── strip-json-comments@1.0.4
│ ├── text-table@0.2.0
│ ├─┬ user-home@2.0.0
│ │ └── os-homedir@1.0.1
│ └── xml-escape@1.0.0
├── eslint-plugin-babel@3.1.0
├── eslint-plugin-react@3.16.1
├── interact.js@1.2.6
├─┬ json-rpc2@1.0.2
│ ├─┬ debug@2.2.0
│ │ └── ms@0.7.1
│ ├─┬ es5class@2.3.1
│ │ └── better-curry@1.6.0
│ ├── eventemitter3@1.2.0
│ ├─┬ faye-websocket@0.11.0
│ │ └─┬ websocket-driver@0.6.4
│ │   └── websocket-extensions@0.1.1
│ ├── jsonparse@1.2.0
│ ├── lodash@3.10.1
│ └── object-assign@4.0.1
├── react@0.14.8 extraneous
├─┬ react-for-atom@0.14.7-0
│ ├─┬ react@0.14.7
│ │ ├─┬ envify@3.4.0
│ │ │ ├─┬ jstransform@10.1.0
│ │ │ │ ├── base62@0.1.1
│ │ │ │ ├── esprima-fb@13001.1001.0-dev-harmony-fb
│ │ │ │ └─┬ source-map@0.1.31
│ │ │ │   └── amdefine@1.0.0
│ │ │ └── through@2.3.8
│ │ └─┬ fbjs@0.6.1
│ │   ├── core-js@1.2.6
│ │   ├─┬ loose-envify@1.1.0
│ │   │ └── js-tokens@1.0.3
│ │   ├─┬ promise@7.1.1
│ │   │ └── asap@2.0.3
│ │   ├── ua-parser-js@0.7.10
│ │   └── whatwg-fetch@0.9.0
│ ├── react-addons-clone-with-props@0.14.7
│ ├── react-addons-create-fragment@0.14.7
│ ├── react-addons-css-transition-group@0.14.7
│ ├── react-addons-linked-state-mixin@0.14.7
│ ├── react-addons-perf@0.14.7
│ ├── react-addons-pure-render-mixin@0.14.7
│ ├── react-addons-shallow-compare@0.14.7
│ ├── react-addons-test-utils@0.14.7
│ ├── react-addons-transition-group@0.14.7
│ ├── react-addons-update@0.14.7
│ └── react-dom@0.14.7
├─┬ react-redux@4.4.1
│ ├── hoist-non-react-statics@1.0.5
│ ├── invariant@2.2.1
│ ├── lodash@4.8.2
│ └─┬ loose-envify@1.1.0
│   └── js-tokens@1.0.3
└─┬ redux@3.3.1
  ├── lodash@4.8.2
  ├── lodash-es@4.8.2
  └─┬ loose-envify@1.1.0
    └── js-tokens@1.0.3

npm ERR! extraneous: react@0.14.8 /Users/sadovnychyi/.atom/packages/go-debug/node_modules/react
```

Could it be related to `npm ERR! extraneous: react`?

**Comment by lloiser** [comment]
Most likely a problem due to the `extraneous` react package.
I don't get the 0.14.8 version even with after a `npm cache clean`.
Which version is inside the `node_modules/react` ?

**Comment by sadovnychyi** [comment]
```bash
~/.atom/packages/go-debug·cat node_modules/react/package.json | grep version
  "version": "0.14.8",
```
It seems like the latest one.

**Comment by lloiser** [comment]
Is the react 0.14.8 specified in the `package.json` of `go-debug`?
There should only be a `react-for-atom 0.14.7-0` , `react-redux ^4.4.1` and `eslint-plugin-react ^3.16.1`

**Comment by sadovnychyi** [comment]
Right, it's not specified in package.json of go-debug, but I'm sure react-for-atom depends on it.
FYI I'm using the latest version of npm
```
~/.atom/packages/go-debug·npm --version                                                             
3.8.5
```
which handles dependencies in different way by unpacking everything it can into root of node_modules.

See https://github.com/npm/npm/releases/tag/v3.0.0

**Comment by lloiser** [comment]
me too so this isn't the problem...

**Comment by lloiser** [comment]
`react-for-atom` has a fixed 0.14.7 version (so no ^ prefix) (https://github.com/jgebhardt/react-for-atom/blob/master/package.json#L21) so this shouldn't be a problem either...

**Comment by sadovnychyi** [comment]
It seems? like react-for-atom works as expected, but I can be wrong here. 
![image](https://cloud.githubusercontent.com/assets/193864/14350009/4829c41e-fcf9-11e5-8e10-7e9259082c8b.png)

**Comment by sadovnychyi** [comment]
Looks like it's works if I import `import { Component } from "react-for-atom";` and then accessing Component directly instead of React.Component in variables.jsx.

But there's more issues like this. Will investigate later. 
Maybe react-for-atom should wrap things properly inside of React object.

**Comment by lloiser** [comment]
this looks completely different than my react-for-atom.js !
It seems that it is still in version 0.14.2 - which (as I can see from the code) provided the react packages differently than the latest react-for-atom version
my first guess is that there is another package you installed that still uses an older version of react-for-atom.
please post your `apm list --installed --bare`

**Comment by sadovnychyi** [comment]
```bash
~/.atom/packages/go-debug·apm list --installed --bare
Chromodynamics@0.0.7
MagicPython@0.5.9
Sublime-Style-Column-Selection@1.4.0
activate-power-mode@0.4.1
atom-beautify@0.29.1
atom-jinja2@0.5.0
atom-pair@2.0.10
atom-ternjs@0.13.2
autocomplete-emojis@2.3.0
autocomplete-go@1.0.6
autocomplete-html@0.7.2
autocomplete-paths@1.0.2
autocomplete-python@1.7.2
box-edit@0.1.3
builder-go@1.0.0
cloud-debugger@0.0.1-0
color-picker@2.1.1
dash@1.6.0
editor-stats@0.17.0
file-icons@1.7.1
git-time-machine@1.4.1
go-config@1.1.4
go-debug@0.1.5
go-get@1.0.3
go-oracle@0.2.1
go-plus@4.1.0
gofmt@1.1.5
gometalinter-linter@1.1.0
gorename@1.0.2
highlight-line@0.11.1
highlight-selected@0.11.2
hyperclick@0.0.35
imdone-atom@1.3.29
keyboard-localization@1.4.18
language-docker@1.1.6
linter@1.11.4
linter-alex@2.0.0
linter-coffeelint@1.1.2
linter-flake8@1.13.0
linter-golinter@1.2.0
linter-js-standard@3.2.1
linter-scss-lint@2.5.1
monokai@0.18.0
navigator-godef@1.0.2
pigments@0.26.0
python-yapf@0.10.0
regex-railroad-diagram@0.16.0
revert-buffer@0.5.0
set-syntax@0.3.0
sort-lines@0.14.0
tester-go@1.0.4
toggle-quotes@1.0.0
welcome@0.34.0
```

**Comment by lloiser** [comment]
the bad package seems to be `facebooknuclideapm/hyperclick`. It has a `react-for-atom @ 0.14.3` ... Unfortunately I don't know what to do next...

**Comment by sadovnychyi** [comment]
So yeah, it's works with hyperclick turned off.

Filled an issue at react-for-atom: https://github.com/jgebhardt/react-for-atom/issues/10
They use global variable to store the react objects, which is the same for different versions.

**Comment by zertosh** [comment]
hyperclick@0.0.36, released 2 days ago, uses an updated react-for-atom so this should be fixed. I got the go-ahead to upstream hyperclick into Atom. In the mean time, while that's going on, I'll be publishing regular updates to hyperclick. We kinda neglected the standalone version after http://nuclide.io/blog/2016/01/13/Nuclide-v0.111.0-The-Unified-Package/. Sorry.
