### ISSUE TITLE
Uncaught TypeError: Cannot read property 'then' of null

### ISSUE THREAD

**Issue by Kliton** [lloiser/go-debug#82]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.14.4 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.3
**Thrown From**: [go-debug](https://github.com/lloiser/go-debug) package 1.1.0

### Stack Trace

Uncaught TypeError: Cannot read property 'then' of null

```
At /Users/kliton/.atom/packages/go-debug/lib/debugger.js:82

TypeError: Cannot read property 'then' of null
    at Debugger.stop (/packages/go-debug/lib/debugger.js:81:59)
    at Object.action (/packages/go-debug/lib/commands.js:73:33)
    at Commands.execute (/packages/go-debug/lib/commands.js:120:23)
    at Panel.handleCommandClick (/packages/go-debug/lib/panel.js:170:25)
```

### Commands

```
     -2:34.7.0 snippets:next-tab-stop (input.hidden-input)
     -2:34.7.0 snippets:expand (input.hidden-input)
     -2:34.7.0 editor:indent (input.hidden-input)
     -2:33.4.0 core:backspace (input.hidden-input)
  2x -2:32.9.0 core:save (input.hidden-input)
     -1:59.4.0 go-debug:toggle-panel (input.hidden-input)
     -1:37.7.0 core:save (input.hidden-input)
  2x -1:34.6.0 go-debug:toggle-panel (input.hidden-input)
     -1:16.8.0 application:new-file (input.hidden-input)
     -1:16.5.0 core:paste (input.hidden-input)
     -1:14.7.0 grammar-selector:show (input.hidden-input)
     -1:13.9.0 core:confirm (input.hidden-input)
     -1:05.7.0 application:new-file (input.hidden-input)
     -1:05.4.0 core:paste (input.hidden-input)
     -0:53.4.0 grammar-selector:show (input.hidden-input)
     -0:52.9.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
an-old-hope-syntax 1.0.2 
atom-beautify 0.29.17 
atom-material-syntax 1.0.2 
busy 0.7.0 
emmet 2.4.3 
file-icons 2.0.10 
fonts 2.0.0 
go-debug 1.1.0 
go-find-references 1.2.3 
go-plus 5.1.0 
go-signature-statusbar 1.2.0 
hyperclick 0.0.39 
isotope-ui 2.7.1 
language-docker 1.1.7 
language-groovy 0.6.0 
language-javascript-jsx 0.3.7 
language-markdown 0.19.1 
language-sql-mysql 0.3.1 
less-than-slash 0.16.0 
linter 1.11.21 
linter-docker 0.1.4 
markdown-pdf 1.5.0 
markdown-preview-plus 2.4.2 
markdown-scroll-sync 2.1.2 
markdown-themeable-pdf 1.2.0 
monokai-seti 0.7.0 
nord-atom-syntax 0.5.0 
nord-atom-ui 0.9.0 
nucleus-dark-ui 0.10.22 
php-debug 0.2.4 
pigments 0.39.0 
platformio-ide-terminal 2.2.2 
react 0.16.2 
react-redux-snippets 0.1.5 
react-snippets 0.7.0 
seti-syntax 1.1.2 
seti-ui 1.4.0 
seti-ui-red 0.13.0 
steam-pirate-syntax 0.3.0 
steam-pirate-ui 0.6.1 
Sublime-Style-Column-Selection 1.7.3 
todo-show 1.9.0 
tool-bar 1.0.1 
webbox-color 0.5.9 
```

**Comment by lloiser** [comment]
fixed with v1.2.0
