### ISSUE TITLE
Uncaught Error: Invalid child node: undefined

### ISSUE THREAD

**Issue by awnumar** [lloiser/go-debug#91]
**Atom**: 1.16.0 x64
**Electron**: 1.4.15
**OS**: linux 4.10.11-1-ARCH
**Thrown From**: [go-debug](https://github.com/lloiser/go-debug) package 1.2.0

### Stack Trace

Uncaught Error: Invalid child node: undefined

```
At /home/awn/.atom/packages/go-debug/node_modules/etch/lib/dom.js:25

Error: Invalid child node: undefined
    at Object.dom (/packages/go-debug/node_modules/etch/lib/dom.js:25:15)
    at /usr/lib/atom/node_modules/incompatible-packages/lib/incompatible-packages-component.js:203:31
    at Array.map (native)
    at IncompatiblePackagesComponent.renderIncompatibleModules (/usr/lib/atom/node_modules/incompatible-packages/lib/incompatible-packages-component.js:199:34)
    at IncompatiblePackagesComponent.renderIncompatiblePackage (/usr/lib/atom/node_modules/incompatible-packages/lib/incompatible-packages-component.js:152:63)
    at Array.map (native)
    at IncompatiblePackagesComponent.renderIncompatiblePackageList (/usr/lib/atom/node_modules/incompatible-packages/lib/incompatible-packages-component.js:128:35)
    at IncompatiblePackagesComponent.render (/usr/lib/atom/node_modules/incompatible-packages/lib/incompatible-packages-component.js:79:14)
    at updateSync (/packages/go-debug/node_modules/etch/lib/component-helpers.js:99:34)
    at /packages/go-debug/node_modules/etch/lib/component-helpers.js:72:7
    at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (/usr/lib/atom/src/view-registry.js:219:9)
    at /usr/lib/atom/src/view-registry.js:3:59
```

### Commands

```
     -0:12.5.0 incompatible-packages:view (div.incompatible-packages-status.inline-block.text.text-error)
```

### Non-Core Packages

```
autocomplete-bibtex 0.7.0 
busy-signal 1.3.0 
go-debug 1.2.0 
go-plus 5.4.0 
go-signature-statusbar 1.2.0 
hyperclick 0.0.40 
intentions 1.1.2 
language-latex 1.0.0 
latex 0.43.0 
latex-completions 0.3.2 
latex-plus 0.9.1 
latexer 0.3.0 
linter 2.1.4 
linter-chktex 1.3.0 
linter-ui-default 1.2.3 
minimap 4.27.1 
outlander-syntax 2.0.0 
outlander-ui 1.4.0 
pdf-view 0.57.0 
wordcount 2.10.4 
```

**Comment by lloiser** [comment]
Most likely not an issue with go-debug.
