### ISSUE TITLE
Uncaught Error: watch ~/workspace/src/bitbucket.org/systemgroup/platform/sapi ENOSPC

### ISSUE THREAD

**Issue by fasilenko** [lloiser/go-debug#93]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Ubuntu 16.04.2
**Thrown From**: [go-debug](https://github.com/lloiser/go-debug) package 1.3.1

### Stack Trace

Uncaught Error: watch /home/stalker/workspace/src/bitbucket.org/systemgroup/platform/sapi ENOSPC

```
At events.js:160

Error: watch /home/stalker/workspace/src/bitbucket.org/systemgroup/platform/sapi ENOSPC
    at exports._errnoException (util.js:1026:11)
    at FSWatcher.start (fs.js:1439:19)
    at Object.fs.watch (fs.js:1466:11)
    at createFsWatchInstance (/packages/go-debug/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/packages/go-debug/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/packages/go-debug/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at FSWatcher.NodeFsHandler._handleDir (/packages/go-debug/node_modules/chokidar/lib/nodefs-handler.js:407:19)
    at /packages/go-debug/node_modules/chokidar/lib/nodefs-handler.js:455:19)
    at /packages/go-debug/node_modules/chokidar/lib/nodefs-handler.js:460:16)
    at FSReqWrap.oncomplete (fs.js:123:15)
```

### Commands

```
```

### Non-Core Packages

```
atom-clock 0.1.7 
busy-signal 1.4.0 
date-plus 1.2.0 
git-plus 7.6.0 
go-debug 1.3.1 
go-plus 5.4.0 
go-signature-statusbar 1.2.0 
hyperclick 0.0.40 
intentions 1.1.2 
linter 2.1.4 
linter-ui-default 1.2.3 
nord-atom-syntax 0.6.0 
nord-atom-ui 0.10.2 
qolor 0.4.1 
```

**Comment by kaikun213** [comment]
Got the same:


**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Ubuntu 16.04.2
**Thrown From**: [go-debug](https://github.com/lloiser/go-debug) package 1.3.1
..
go-debug 1.3.1 
go-plus 5.4.0

**Comment by lloiser** [comment]
This issues seems related https://github.com/lloiser/go-debug/issues/73. Does this solve your problem?

**Comment by lloiser** [comment]
No response. Please reopen if the error still happens after reading through the previously mentioned issue.
