### ISSUE TITLE
Uncaught NotFoundError: Failed to execute 'insertBefore' on 'Node': The node before which the new...

### ISSUE THREAD

**Issue by gotomgo** [lloiser/go-debug#98]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.17.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.4
**Thrown From**: [go-debug](https://github.com/lloiser/go-debug) package 1.3.1

### Stack Trace

Uncaught NotFoundError: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.

```
At /Users/tomguinther/.atom/packages/go-debug/node_modules/etch/lib/patch.js:97

Error: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
    at Error (native)
    at updateChildren (/packages/go-debug/node_modules/etch/lib/patch.js:97:23)
    at patch (/packages/go-debug/node_modules/etch/lib/patch.js:18:9)
    at updateChildren (/packages/go-debug/node_modules/etch/lib/patch.js:75:7)
    at patch (/packages/go-debug/node_modules/etch/lib/patch.js:18:9)
    at updateSync (/packages/go-debug/node_modules/etch/lib/component-helpers.js:108:20)
    at /packages/go-debug/node_modules/etch/lib/component-helpers.js:72:7
    at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (/Applications/Atom.app/Contents/Resources/app/src/view-registry.js:223:1)
    at /Applications/Atom.app/Contents/Resources/app/src/view-registry.js:3:1
```

### Commands

```
     -1:05.5.0 golang:godef (span.syntax--support.syntax--function.syntax--go)
     -1:00.7.0 core:copy (input.hidden-input)
     -0:57.1.0 core:paste (input.hidden-input)
  4x -0:47.7.0 core:backspace (input.hidden-input)
     -0:45.1.0 core:move-down (input.hidden-input)
     -0:44.9.0 autocomplete-plus:confirm (input.hidden-input)
     -0:44.2.0 core:save (input.hidden-input)
  7x -0:35.7.0 core:delete (input.hidden-input)
     -0:33.2.0 core:save (input.hidden-input)
  2x -0:30.4.0 core:backspace (input.hidden-input)
     -0:29.1.0 core:save (input.hidden-input)
     -0:20.8.0 golang:find-usage (span.syntax--variable.syntax--other.syntax--assignment.syntax--go)
     -0:10.4.0 core:backspace (input.hidden-input)
     -0:08.7.0 core:save (input.hidden-input)
     -0:07.0 core:move-down (input.hidden-input)
```

### Non-Core Packages

```
busy-signal 1.4.1 
git-plus 7.8.0 
go-debug 1.3.1 
go-plus 5.5.2 
go-signature-statusbar 1.2.0 
hyperclick 0.0.40 
intentions 1.1.2 
linter 2.1.4 
linter-ui-default 1.2.4 
terminal-plus 0.14.5 
```

**Comment by lloiser** [comment]
please upgrade `go-plus` to the latest version
